Feature
othman-19/tic_tac_toe-JS pull request #1
Opened 2019-11-21 11:12 UTC by sumaerjolly

2019-11-21 16:16 UTC, SunnyAsar requested changes
# Hi @sumaerjolly  and @othman-19  👋 
### Good job on this project, It works!!
To make it better let's work on our code composition, below i have made some comments, lets consider them and make some updates.

**Please request another review when the updates are done.**

2019-11-21 16:16 UTC, SunnyAsar commented on script.js
> +})();
let's simplify player1 and player2 with a loop, and do it at game start.

2019-11-21 16:16 UTC, SunnyAsar commented on script.js
> +let boardArray = [0, 1, 2, 3, 4, 5, 6, 7, 8];
let's also avoid code.

2019-11-21 16:16 UTC, SunnyAsar commented on script.js
> +}
we have multiple methods for displaying message, lets use just one.

2019-11-22 11:04 UTC, shloch approved these changes
### Hello @sumaerjolly  and @othman-19  👋

Great job, please dont forget to include the link of live demo in your README before merging

## This project is considered valid 😊😊😊

2019-11-22 11:30 UTC, merged